### ISSUE TITLE
extend openRGB

### ISSUE THREAD

**Issue by denk-mal** [zauguin/libx50q#1]
It would be nice if you extend openRGB (https://gitlab.com/CalcProgrammer1/OpenRGB) for the X50Q. There is already a Controller for the Q4/Q5 that maybe a base for the X50Q.

**Comment by zauguin** [comment]
> There is already a Controller for the Q4/Q5 that maybe a base for the X50Q.

They use very different protocols

> It would be nice if you extend openRGB (https://gitlab.com/CalcProgrammer1/OpenRGB) for the X50Q.

I'm personallt not using or want to use openRGB at the moment and I generally dislike working on GPL code, so this is not currently planned.

If anyone wants to work on this though and has any questions, I'm happy to help.

**Comment by denk-mal** [comment]
> > There is already a Controller for the Q4/Q5 that maybe a base for the X50Q.
> 
> They use very different protocols

I know because I am the developer of those controller :-)
 
> > It would be nice if you extend openRGB (https://gitlab.com/CalcProgrammer1/OpenRGB) for the X50Q.
> 
> I'm personallt not using or want to use openRGB at the moment and I generally dislike working on GPL code, so this is not currently planned.

Accepted.
 
> If anyone wants to work on this though and has any questions, I'm happy to help.

No, sorry. I am not having a X50Q (and I would not buy another DAS Keyboard again)
